### ISSUE TITLE
Won't start in docker

### ISSUE THREAD

**Issue by rusty1281** [osminogin/tornote#7]
Hello,

I have build this app in a docker image with 0 errors but when starting it I get the following output:

```
panic: open templates/index.html: no such file or directory


goroutine 1 [running]:

github.com/osminogin/tornote.(*server).Init(0xc000211890)

	/go/src/app/server.go:151 +0x57a

main.main()

	/go/src/app/cmd/tornote/main.go:57 +0x35b
```

Any help on the matter? 

Tnx!

**Comment by osminogin** [comment]
I'm fixed Dockerfile. 

Please check

**Comment by rusty1281** [comment]
New error on the matter:

`2020/07/10 08:30:31 dial tcp 127.0.0.1:5432: connect: connection refused`

no matter if I pull it from hub or build it myself

**Comment by osminogin** [comment]
It is ok. You *must* set right `DATABASE_URL` evironment setting to your postgres.

**Comment by rusty1281** [comment]
What exact format is needed for that variable? Can't see anything in the documentation.

tnx again!

**Comment by osminogin** [comment]
This is DSN. Looks like this `postgres://pguser:s3cr3t@youthost:5432/dbname`

I will add this information in readme soon.

**Comment by osminogin** [comment]
Of course, write permissions to this base.

**Comment by rusty1281** [comment]
> This is DSN. Looks like this `postgres://pguser:s3cr3t@youthost:5432/dbname`
> 
> I will add this information in readme soon.

Ok so the default one. Great, tnx. Will try it right now and post back. Tnx for your time and help so far.

**Comment by rusty1281** [comment]
DB problem solved now. Atm I get this warning and the container stops:

`2020/07/10 09:02:46 pg: SSL is not enabled on the server`

**Comment by osminogin** [comment]
This is already to the ORM library that works with PostgresSQL. 

The solution is here (add additional connection parameter to disable SSL):

https://stackoverflow.com/a/51642783/1068313

**Comment by rusty1281** [comment]
Was just about to write back that I have added sslmode=disable and now it works. The site will load but I get a blank page apart from the header `tornoteherokuapp.com`

Am I missing something else here?

**Comment by osminogin** [comment]
Another minor fix commited. 

It should help, but I can check out later in the evening.

**Comment by osminogin** [comment]
These are small residual effects after refactoring.

Now HTML, CSS and JS files is not compiled into a binary, but goes separately (making it possible to modify them without recompile), but binary must find them in expected location

**Comment by rusty1281** [comment]
Excellent! Now it works. 

Thanks again for your help and speed. Really appreciated.

**Comment by osminogin** [comment]
No problem.

If you have any suggestions or some PR improving the project I will be grateful. The project is a bit in a frozen state, but it is possible to make a free and more functional clone of the privnote

**Comment by rusty1281** [comment]
Looks like I have spoken too soon. The site loads but the "Creat note" button is not triggering anything. Also no error in the container log.

I see that all the elements have loaded so far. Running this in local atm.

Web inspector reports:
`Failed to load resource: the server responded with a status of 403 (Forbidden)` for http://myaddress/note
`Forbidden - CSRF token invalid`

**Comment by osminogin** [comment]
OK. 

I check this later.

**Comment by rusty1281** [comment]
Thank you again.

**Comment by osminogin** [comment]
Made another fix. Please try

You also must set environment var `SECRET_KEY` (for the form to work correctly).

**Comment by rusty1281** [comment]
Hello, thank again for your time. I have added the new variable with a 30 char long string (random) that includes letters, numbers and special charaters. But I still get the 403 forbidden error when clicking on the Create note button. No errors in the logs.

**Comment by rusty1281** [comment]
I have noticed the changes in main.go file regarding the addition of SECRET_KEY variable but also noticed that there is a PORT variable alongside DATABASE_URL and SECRET_KEY, so I tried adding that as a variable as well and set it to 8000 (as a default) but still no joy. Also, I have tried to change the KEY value to a log number only value, but again, 403 error when I click the button.

**Comment by osminogin** [comment]
I'm unable to reproduce this error. I deployed a new version on Heroku - it works without changes, tried to play it locally with Docker - I also cann't get this error.

Running with that command:

`docker run -p 8000:8000 -e DATABASE_URL=... -e SECRET_KEY=12312512312312312312 tornote`

And notes created correctly on http://localhost:8000

Maybe these are some limitations of addons in the browser? You can try another browser without addons?

Also try comment CSRF middleware in `server.go` line 142, I think that helps, but is not solution for production.

**Comment by rusty1281** [comment]
I have tried with multiple browsers that have no addons running at all (even in private mode) but I still get the 403. I am accessing it using my docker host IP address, not localhost. Also, it is running on a custom local port (I have tried running it on 8000 as well) but still, it loads up fine, but the Create button returns CSFR error (403 Forbidden). 

I have also tried running with the PORT variable that I would set to my custom local port but then the container would not boot up at all. So, running it with or without PORT variable on 8000 I still get the error.

Could there be a PostgresDB side problem? Encoding or something like that? I can see that the table "notes" has been created along with everything else needed so not sure that there is the problem.

Browsers I have tested are Safari and Firefox.

Tnx for your time and effort on the matter. If there are any logs I could send to capture this error and its origin, let me know.

**Comment by osminogin** [comment]
Looks like it is worked now. 

New setting `PRODUCTION` added, disabled by default for local run and development.

In production mode connection must be over https only or you will get 403 Forbidden error.

Also, be sure to delete the old cookies.

**Comment by rusty1281** [comment]
Sorry for the late reply. I can confirm that it is indeed working now via https :D. Thank you again for your help on the matter.
